name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: kube-logging/logging-operator/.github/workflows/artifacts.yaml@5.3.0
    with:
      version: ${{ github.ref_name }}
      publish: true
      release: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
